[deps]
netcdf4 = ""
matplotlib = ""
zarr = ""
r = ""
r-sf = ""
r-stars = ""
r-maps = ""
r-lubridate = ""
r-rnaturalearth = ""
rioxarray = ""
r-raster = ""
xarray = ""
h5py = ""
dask = ""
jupyter = ""
rasterio = ""
cartopy = ""
geopandas = ""
r-rnaturalearthdata = ""
libnetcdf = ""
